#!/bin/bash -e
# install script for Fuettr Server and Java-Application

THISUSER=/home/$USER

echo -e "\e[92m
--> downloading and installing node.js...\e[0m"
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y nodejs

echo -e "\e[92m
--> downloading and installing git...\e[0m"
sudo apt install -y git
sudo apt install -y rpl
sudo apt -y autoremove

echo -e "\e[92m
--> downloading and installing mongodb...\e[0m"
sudo adduser --ingroup nogroup --shell /etc/false --disabled-password --gecos "" \
--no-create-home mongodb &

sudo rm -R mongodb/
mkdir mongodb
cd mongodb
wget http://andyfelong.com/downloads/mongodb_stretch_3_0_14_core.zip
unzip mongodb_stretch_3_0_14_core.zip
cd core
sudo chown root:root mongo* && sudo chmod 755 mongo* && sudo strip mongo* && sudo cp -p mongo* /usr/bin
sudo rm -R /var/log/mongodb
sudo mkdir /var/log/mongodb
sudo chown mongodb:nogroup /var/log/mongodb
sudo rm -R /var/lib/mongodb
sudo mkdir /var/lib/mongodb
sudo chown mongodb:root /var/lib/mongodb
sudo chmod 775 /var/lib/mongodb
sudo rm -R /etc/mongodb.conf
echo "# /etc/mongodb.conf
# minimal config file (old style)
# Run mongod --help to see a list of options

bind_ip = 127.0.0.1
quiet = true
dbpath = /var/lib/mongodb
logpath = /var/log/mongodb/mongod.log
logappend = true
storageEngine = mmapv1" | sudo tee /etc/mongodb.conf

sudo rm -R /lib/systemd/system/mongodb.service
echo "[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target

[Service]
User=mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongodb.conf

[Install]
WantedBy=multi-user.target" | sudo tee /lib/systemd/system/mongodb.service

echo -e "\e[92m
--> setting git credentials...\e[0m"
git config --global user.name "fuettr"
git config --global user.email "fuettr@gmail.com"

echo -e "\e[92m
--> create logfolder...\e[0m"
cd /var/log && sudo mkdir fuettr
sudo chown $USER /var/log/fuettr
chmod 755 /var/log/fuettr

echo -e "\e[92m
--> downloading...\e[0m"
cd $THISUSER && mkdir git
sudo chown $USER $THISUSER/git
chmod 755 $THISUSER/git
cd $THISUSER/git && git clone https://github.com/Katzenfuetterungsanlage/fuettr.git
cd $THISUSER/git/fuettr && git reset --hard
cd $THISUSER/git/fuettr && git pull

echo -e "\e[92m
--> copy rc.local...\e[0m"
sudo rsync -aP $THISUSER/git/fuettr/rc.local /etc/rc.local

echo -e "\e[92m
--> editing rc.local...\e[0m"
sudo rpl HOMEE $THISUSER /etc/rc.local
sudo rpl USERR $USER /etc/rc.local
sudo chmod +x /etc/rc.local

echo -e "\e[92m
--> copying autostart...\e[0m"
rsync -aP $THISUSER/git/fuettr/autostart $THISUSER/.config/lxsession/LXDE-$USER/autostart

echo -e "\e[92m
--> edititng autostart...\e[0m"
rpl USERR $THISUSER $THISUSER/.config/lxsession/LXDE-$USER/autostart

echo -e "\e[92m
--> getting serialnumber...\e[0m"
IFACE=$(ip route show default | awk '/default/ {print $5}' )
read MAC </sys/class/net/$IFACE/address
JSON={\"mac\":\"$MAC\"}
curl -X POST \
-H "Content-type: application/json" \
-d $JSON \
'sorogon.duckdns.org:2525/serialnumber' < $THISUSER/git/fuettr/seriennummer

echo -e "\e[92m
--> installing node dependencies...\e[0m"
sudo npm i -g npm
sudo npm i -g @angular/cli gulp npm-install-missing
cd $THISUSER/git/fuettr/Webserver/ng2 && sudo npm i --unsafe-perm
cd $THISUSER/git/fuettr/Webserver/server && sudo npm i

echo -e "\e[92m
--> initializing database...\e[0m"
sudo systemctl start mongodb
sudo mongod &

echo -e "\e[92m
--> building server...\e[0m"
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 17325
cd $THISUSER/git/fuettr/Webserver/ng2 && sudo ng build
cd $THISUSER/git/fuettr/Webserver/server && sudo gulp cleanAndBuild

echo -e "\e[92m
--> starting server...\e[0m"
cd $THISUSER/git/fuettr/Webserver/server/dist && node main.js #&

echo -e "\e[92m
--> starting java application...\e[0m"
cd $THISUSER/git/fuettr/Diplomarbeit_Project/dist && java -jar Diplomarbeit_Project.jar &

echo -e "\e[92m
done\e[0m"
