#!/bin/bash -e
# install script for Fuettr Server and Java-Application

THISUSER=/home/$USER

read -p 'Please enter the Board you are using: ' internal

echo -e "\e[92m
--> downloading and installing node.js...\e[0m"
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt install -y nodejs

echo -e "\e[92m
--> downloading and installing ant...\e[0m"
sudo apt install -y ant

echo -e "\e[92m
--> downloading and installing git...\e[0m"
sudo apt install -y git
sudo apt install -y rpl

echo -e "\e[92m
--> downloading and installing mongodb...\e[0m"
sudo apt install -y mongodb-server
sudo apt -y autoremove

echo -e "\e[92m
--> setting git credentials...\e[0m"
git config --global user.name "fuettr"
git config --global user.email "fuettr@gmail.com"

echo -e "\e[92m
--> create logfolder...\e[0m"
cd /var/log && sudo mkdir fuettr
sudo chown $USER /var/log/fuettr
chmod 755 /var/log/fuettr

echo -e "\e[92m
--> downloading...\e[0m"
cd $THISUSER && mkdir git
sudo chown $USER $THISUSER/git
chmod 755 $THISUSER/git
cd $THISUSER/git && git clone https://github.com/Katzenfuetterungsanlage/fuettr.git
cd $THISUSER/git/fuettr && git reset --hard
cd $THISUSER/git/fuettr && git pull

echo $internal >> $THISUSER/git/fuettr/internal

echo -e "\e[92m
--> copy rc.local...\e[0m"
sudo rsync -aP $THISUSER/git/fuettr/rc.local /etc/rc.local

echo -e "\e[92m
--> editing rc.local...\e[0m"
sudo rpl HOMEE $THISUSER /etc/rc.local
sudo rpl USERR $USER /etc/rc.local
sudo chmod +x /etc/rc.local

echo -e "\e[92m
--> copying autostart...\e[0m"
rsync -aP $THISUSER/git/fuettr/autostart $THISUSER/.config/lxsession/LXDE-$USER/autostart

echo -e "\e[92m
--> edititng autostart...\e[0m"
rpl USERR $THISUSER $THISUSER/.config/lxsession/LXDE-$USER/autostart

echo -e "\e[92m
--> getting serialnumber...\e[0m"
IFACE=$(ip route show default | awk '/default/ {print $5}')
IFACES=( $IFACE )
IIFACE=${IFACES[0]}
read MAC < /sys/class/net/$IIFACE/address
JSON={\"mac\":\"$MAC\"}
curl -X POST \
-H "Content-type: application/json" \
-d $JSON \
'sorogon.duckdns.org:2525/serialnumber' >>$THISUSER/git/fuettr/seriennummer

echo -e "\e[92m
--> installing node dependencies...\e[0m"
sudo npm i -g npm
sudo npm i -g @angular/cli gulp npm-install-missing
cd $THISUSER/git/fuettr/Webserver/ng2 && sudo npm i --unsafe-perm
cd $THISUSER/git/fuettr/Webserver/server && sudo npm i

echo -e "\e[92m
--> initializing database...\e[0m"
sudo mkdir -p /data/db
sudo systemctl start mongodb

echo -e "\e[92m
--> building server...\e[0m"
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 17325
cd $THISUSER/git/fuettr/Webserver/ng2 && sudo ng build
cd $THISUSER/git/fuettr/Webserver/server && sudo gulp cleanAndBuild

#echo -e "\e[92m
#--> building java program...\e[0m"
#cd $THISUSER/git/fuettr/Diplomarbeit_Projekt && ant jar

echo -e "\e[92m
--> starting server...\e[0m"
cd $THISUSER/git/fuettr/Webserver/server/dist && node main.js &

echo -e "\e[92m
--> starting java application...\e[0m"
cd $THISUSER/git/fuettr/Diplomarbeit_Projekt/dist && java -jar Fuettr.jar &

echo -e "\e[92m
done\e[0m"

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  echo "
\e[41m My IP address is \e[30m$_IP\e[0m\n"
fi
